In [1]:
import pandas as pd

In [2]:
# Series-:
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)
print(series[0])
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
1
<class 'pandas.core.series.Series'>

In [3]:
# Series from dictionary-:
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
data=[10,20,30]
index=['a','b','c']

pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

In [29]:
# DataFrame-:
# Dataframe from dictionary of list-:

data = {
    'Name':['Omkar','John','Jack'],
    'Age':[25,30,45],
    'City':['Mumbai','Kota','Jaipur']
}

df = pd.DataFrame(data)
print(df)
print(df['Name'][0])
print(df['Name'][1])
print(df['Age'][0])
print(df['Age'][1])
print(type(df))

    Name  Age    City
0  Omkar   25  Mumbai
1   John   30    Kota
2   Jack   45  Jaipur
Omkar
John
25
30
<class 'pandas.core.frame.DataFrame'>

In [16]:
import numpy as np
np.array(df)

array([['Omkar', 25, 'Mumbai'],
       ['John', 30, 'Kota'],
       ['Jack', 45, 'Jaipur']], dtype=object)

In [20]:
# DataFrame from a List of Dictionaries-:
data = [
 {'Name':'Omkar','Age':25,'City':'Mumbai'},
 {'Name':'Raut','Age':35,'City':'Jaipur'},
 {'Name':'Suresh','Age':22,'City':'Firang'}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age    City
0   Omkar   25  Mumbai
1    Raut   35  Jaipur
2  Suresh   22  Firang
<class 'pandas.core.frame.DataFrame'>

In [25]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [26]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [31]:
# Accessing Data from DataFrame-:
df

    Name  Age    City
0  Omkar   25  Mumbai
1   John   30    Kota
2   Jack   45  Jaipur

In [36]:
print(df['Name'])
print(type(df['Name']))

0    Omkar
1     John
2     Jack
Name: Name, dtype: object
<class 'pandas.core.series.Series'>

In [37]:
df.Age

0    25
1    30
2    45
Name: Age, dtype: int64

In [38]:
df.Name

0    Omkar
1     John
2     Jack
Name: Name, dtype: object

In [39]:
df.City

0    Mumbai
1      Kota
2    Jaipur
Name: City, dtype: object

In [45]:
df

    Name  Age    City
0  Omkar   25  Mumbai
1   John   30    Kota
2   Jack   45  Jaipur

In [54]:
df.loc[1:,'Age']

1    30
2    45
Name: Age, dtype: int64

In [59]:
df.loc[2,:]

Name      Jack
Age         45
City    Jaipur
Name: 2, dtype: object

In [53]:
df.iloc[:,0]

0    Omkar
1     John
2     Jack
Name: Name, dtype: object

In [58]:
print(df.iloc[0,2])
print(df.iloc[0,1])

Mumbai
25

In [61]:
df.loc[0]

Name     Omkar
Age         25
City    Mumbai
Name: 0, dtype: object

In [62]:
df.iloc[0]

Name     Omkar
Age         25
City    Mumbai
Name: 0, dtype: object

In [60]:
df['Name']

0    Omkar
1     John
2     Jack
Name: Name, dtype: object

In [65]:
df

    Name  Age    City
0  Omkar   25  Mumbai
1   John   30    Kota
2   Jack   45  Jaipur

In [66]:
df.loc[0,'Name']

'Omkar'

In [67]:
## Accessing a specified element
df.at[0,'Name']

'Omkar'

In [68]:
print(df.at[2,'Age'])

45

In [69]:
print(df.at[2,'Name'])

Jack

In [70]:
print(df.at[2,'City'])

Jaipur

In [79]:
## Accessing a specified element using iat
print(df.iat[1,2])
print(df.iat[0,2])
print(df.iat[2,0])

Kota
Mumbai
Jack

In [80]:
df

    Name  Age    City
0  Omkar   25  Mumbai
1   John   30    Kota
2   Jack   45  Jaipur

In [84]:
# Data Manipulation with DataFrame-:
df["Salary"] = [20000,10000,15000]

In [85]:
df

    Name  Age    City  Salary
0  Omkar   25  Mumbai   20000
1   John   30    Kota   10000
2   Jack   45  Jaipur   15000

In [88]:
df_sal = df.drop("Salary",axis=1)

In [89]:
df_sal

    Name  Age    City
0  Omkar   25  Mumbai
1   John   30    Kota
2   Jack   45  Jaipur

In [90]:
df

    Name  Age    City  Salary
0  Omkar   25  Mumbai   20000
1   John   30    Kota   10000
2   Jack   45  Jaipur   15000

In [91]:
df_sal

    Name  Age    City
0  Omkar   25  Mumbai
1   John   30    Kota
2   Jack   45  Jaipur

In [92]:
df.drop("Salary",axis=1,inplace=True)

In [93]:
df

    Name  Age    City
0  Omkar   25  Mumbai
1   John   30    Kota
2   Jack   45  Jaipur

In [94]:
# Add age to the column-:
df['Age'] = df['Age']+1

In [95]:
df

    Name  Age    City
0  Omkar   26  Mumbai
1   John   31    Kota
2   Jack   46  Jaipur

In [96]:
df.drop(0,inplace=True)

In [97]:
df

   Name  Age    City
1  John   31    Kota
2  Jack   46  Jaipur

In [98]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [99]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [100]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000