In [1]:
import pandas as pd

In [3]:
df_csv = pd.read_csv('sales_data.csv')

In [4]:
df_csv.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [5]:
df_csv.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [8]:
df_csv

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [9]:
df_csv.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [11]:
df_csv.dtypes

Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [16]:
df_csv.dtypes["Region"]
df_csv.dtypes[:3]

Transaction ID       int64
Date                object
Product Category    object
dtype: object

In [19]:
df_csv.isnull().any(axis=0)
df_csv.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
235    False
236    False
237    False
238    False
239    False
Length: 240, dtype: bool

In [21]:
df_csv

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [27]:
df_csv.rename(columns={"Region":"Area"})
df_csv["Unit Price"].astype(int)
df_csv["Unit Price"].apply(lambda x:x/2)

0      499.995
1      249.995
2       34.995
3        7.995
4       44.995
        ...
235     79.995
236     45.000
237      5.495
238     27.500
239     14.995
Name: Unit Price, Length: 240, dtype: float64

In [29]:
df_csv

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [33]:
df_csv.groupby(["Product Category","Payment Method"])["Total Revenue"].sum()

Product Category  Payment Method
Beauty Products   PayPal             2621.90
Books             Credit Card        1861.93
Clothing          Debit Card         8128.93
Electronics       Credit Card       34982.41
Home Appliances   PayPal            18646.16
Sports            Credit Card       14326.52
Name: Total Revenue, dtype: float64

In [34]:
df_csv.groupby(["Product Category","Payment Method"])["Total Revenue"].mean()

Product Category  Payment Method
Beauty Products   PayPal             65.54750
Books             Credit Card        46.54825
Clothing          Debit Card        203.22325
Electronics       Credit Card       874.56025
Home Appliances   PayPal            466.15400
Sports            Credit Card       358.16300
Name: Total Revenue, dtype: float64

In [35]:
df_csv.groupby(["Product Category","Payment Method"])["Total Revenue"].count()

Product Category  Payment Method
Beauty Products   PayPal            40
Books             Credit Card       40
Clothing          Debit Card        40
Electronics       Credit Card       40
Home Appliances   PayPal            40
Sports            Credit Card       40
Name: Total Revenue, dtype: int64

In [39]:
df_csv.groupby(["Product Category","Payment Method"])["Total Revenue"].agg(['mean','median','sum','count'])

                                      mean   median       sum  count
Product Category Payment Method
Beauty Products  PayPal           65.54750   50.995   2621.90     40
Books            Credit Card      46.54825   38.475   1861.93     40
Clothing         Debit Card      203.22325  179.970   8128.93     40
Electronics      Credit Card     874.56025  674.985  34982.41     40
Home Appliances  PayPal          466.15400  388.995  18646.16     40
Sports           Credit Card     358.16300  259.980  14326.52     40

In [46]:
df_csv["Product Category"].mode()[0]

'Beauty Products'

In [49]:
df_csv["Product Category"].mode()[:3]

0    Beauty Products
1              Books
2           Clothing
Name: Product Category, dtype: object

In [50]:
df_csv["Product Category"].mode()

0    Beauty Products
1              Books
2           Clothing
3        Electronics
4    Home Appliances
5             Sports
Name: Product Category, dtype: object