In [22]:
# Target Guided Ordinal Encoding is a manual ordinal technique.

In [23]:
import pandas as pd
df = pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','Paris'],
    'price':[200,150,300,250,100,320]
})

In [24]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    100
5     Paris    320

In [25]:
mean_map = df.groupby('city')['price'].mean().to_dict()

In [26]:
mean_map

{'London': 150.0, 'New York': 150.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [27]:
df['city_encoded'] = df['city'].map(mean_map)

In [28]:
df

       city  price  city_encoded
0  New York    200         150.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    100         150.0
5     Paris    320         310.0

In [29]:
df[["price","city_encoded"]]

   price  city_encoded
0    200         150.0
1    150         150.0
2    300         310.0
3    250         250.0
4    100         150.0
5    320         310.0

In [30]:
# Here’s a clear explanation:

# Monotonic:

# A relationship that always moves in one direction — either only increasing or only decreasing.

# Example: Age vs. Income (if income consistently rises with age) → monotonic increasing.

# Non-monotonic:

# A relationship that changes direction — sometimes increases, sometimes decreases.

# Example: Hours of study vs. Stress (stress may increase at first, then decrease after a point) → non-monotonic.

# In short:

# Monotonic = always one-directional, Non-monotonic = direction changes.

In [32]:
import seaborn as sns
df_tip = sns.load_dataset('tips')

In [33]:
df_tip

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [35]:
# observed in groupby() means:
# It controls whether pandas groups only existing categories or all possible categories of a categorical column.

# Simple:
# observed=False → include all categories (even those not present in data)
# observed=True → include only categories that actually appear

# In one line:
# observed decides if grouping uses all categories or only observed (present) categories.

In [43]:
time_map = df_tip.groupby("time", observed=True)["total_bill"].mean().round(2).to_dict()

In [50]:
df_tip["time_encoded"] = df_tip["time"].map(time_map)

In [56]:
df_tip[df_tip["time"]=="Dinner"]

     total_bill   tip     sex smoker   day    time  size time_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2         20.8
1         10.34  1.66    Male     No   Sun  Dinner     3         20.8
2         21.01  3.50    Male     No   Sun  Dinner     3         20.8
3         23.68  3.31    Male     No   Sun  Dinner     2         20.8
4         24.59  3.61  Female     No   Sun  Dinner     4         20.8
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3         20.8
240       27.18  2.00  Female    Yes   Sat  Dinner     2         20.8
241       22.67  2.00    Male    Yes   Sat  Dinner     2         20.8
242       17.82  1.75    Male     No   Sat  Dinner     2         20.8
243       18.78  3.00  Female     No  Thur  Dinner     2         20.8

[176 rows x 8 columns]

In [57]:
df_tip[df_tip["time"]=="Lunch"]

     total_bill   tip     sex smoker   day   time  size time_encoded
77        27.20  4.00    Male     No  Thur  Lunch     4        17.17
78        22.76  3.00    Male     No  Thur  Lunch     2        17.17
79        17.29  2.71    Male     No  Thur  Lunch     2        17.17
80        19.44  3.00    Male    Yes  Thur  Lunch     2        17.17
81        16.66  3.40    Male     No  Thur  Lunch     2        17.17
..          ...   ...     ...    ...   ...    ...   ...          ...
222        8.58  1.92    Male    Yes   Fri  Lunch     1        17.17
223       15.98  3.00  Female     No   Fri  Lunch     3        17.17
224       13.42  1.58    Male    Yes   Fri  Lunch     2        17.17
225       16.27  2.50  Female    Yes   Fri  Lunch     2        17.17
226       10.09  2.00  Female    Yes   Fri  Lunch     2        17.17

[68 rows x 8 columns]

In [61]:
df_tip.drop("time",axis=1,inplace=True)

In [62]:
df_tip

     total_bill   tip     sex smoker   day  size time_encoded
0         16.99  1.01  Female     No   Sun     2         20.8
1         10.34  1.66    Male     No   Sun     3         20.8
2         21.01  3.50    Male     No   Sun     3         20.8
3         23.68  3.31    Male     No   Sun     2         20.8
4         24.59  3.61  Female     No   Sun     4         20.8
..          ...   ...     ...    ...   ...   ...          ...
239       29.03  5.92    Male     No   Sat     3         20.8
240       27.18  2.00  Female    Yes   Sat     2         20.8
241       22.67  2.00    Male    Yes   Sat     2         20.8
242       17.82  1.75    Male     No   Sat     2         20.8
243       18.78  3.00  Female     No  Thur     2         20.8

[244 rows x 7 columns]