### Standardization

In [15]:
import pandas as pd
import seaborn as sns

In [16]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [17]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [18]:
df['age'].fillna(df.age.median(),inplace=True)

C:\Users\Omkar Raut\AppData\Local\Temp\ipykernel_16244\875218042.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df.age.median(),inplace=True)

In [19]:
df.isna().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [20]:
df = df[['survived','pclass','age','fare']]
# Independent and Dependent Features-:
df

     survived  pclass   age     fare
0           0       3  22.0   7.2500
1           1       1  38.0  71.2833
2           1       3  26.0   7.9250
3           1       1  35.0  53.1000
4           0       3  35.0   8.0500
..        ...     ...   ...      ...
886         0       2  27.0  13.0000
887         1       1  19.0  30.0000
888         0       3  28.0  23.4500
889         1       1  26.0  30.0000
890         0       3  32.0   7.7500

[891 rows x 4 columns]

In [21]:
# Independent and Dependent Features-:
X = df.iloc[:,1:] #Independent
Y = df.iloc[:,0]  #dependent

In [22]:
X

     pclass   age     fare
0         3  22.0   7.2500
1         1  38.0  71.2833
2         3  26.0   7.9250
3         1  35.0  53.1000
4         3  35.0   8.0500
..      ...   ...      ...
886       2  27.0  13.0000
887       1  19.0  30.0000
888       3  28.0  23.4500
889       1  26.0  30.0000
890       3  32.0   7.7500

[891 rows x 3 columns]

In [23]:
# train_test_split is used to split a dataset into training and testing sets.
# Training set → used to train the model
# Test set → used to evaluate model performance
# 📌 Commonly used in machine learning to check how well a model generalizes to new data.

# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
# 👉 Here, 80% data for training and 20% for testing.

In [24]:
# It is very important to do train_test_split cuase we don't want to overfit the Model.

# Overfitting means the model memorizes the training data instead of learning patterns, so it works well on training data but fails on new data.

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.33,)

In [26]:
X_train

     pclass   age      fare
549       2   8.0   36.7500
751       3   6.0   12.4750
430       1  28.0   26.5500
656       3  28.0    7.8958
319       1  40.0  134.5000
..      ...   ...       ...
266       3  16.0   39.6875
109       3  28.0   24.1500
339       1  45.0   35.5000
465       3  38.0    7.0500
685       2  25.0   41.5792

[596 rows x 3 columns]

In [27]:
# For standardization: We use the Standardscaler from sklearn library-:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [29]:
X_train_scaled

array([[-0.38277387, -1.65008187,  0.0845266 ],
       [ 0.82428024, -1.80570415, -0.40222634],
       [-1.58982797, -0.09385904, -0.11999987],
       ...,
       [-1.58982797,  1.22893037,  0.05946208],
       [ 0.82428024,  0.68425238, -0.51100635],
       [-0.38277387, -0.32729246,  0.18135985]], shape=(596, 3))